In [12]:
import numpy as np
import pandas as pd
import seaborn as sns

In [13]:
df = pd.read_csv("/workspaces/machine_learning_codespaces-jupyter/data/customer.csv")

In [14]:
df.sample(5)

    age  gender   review education purchased
6    18    Male     Good    School        No
46   64  Female     Poor        PG        No
45   61    Male     Poor        PG       Yes
47   38  Female     Good        PG       Yes
29   83  Female  Average        UG       Yes

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [16]:
from sklearn.preprocessing import OrdinalEncoder

In [17]:
X_train

    age  gender
14   15    Male
31   22  Female
15   75    Male
2    70  Female
26   53  Female
47   38  Female
22   18  Female
48   39  Female
35   74    Male
43   27    Male
37   94    Male
10   98  Female
4    16  Female
36   34  Female
9    74    Male
34   86    Male
8    65  Female
29   83  Female
0    30  Female
16   59    Male
40   39    Male
30   73    Male
17   22  Female
27   69  Female
3    72  Female
49   25  Female
12   51    Male
33   89  Female
24   16  Female
28   48    Male
42   30  Female
32   92    Male
39   76    Male
46   64  Female
18   19    Male
23   96  Female
11   74    Male
13   57  Female
6    18    Male
38   45  Female

In [20]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [21]:
oe.fit(X_train)

ValueError: invalid literal for int() with base 10: 'Poor'